theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_buttons1 : "bold,italic,underline,|,numlist,bullist"
theme_advanced_buttons2 : ""
theme_advanced_buttons3 : ""
force_br_newlines : true
force_p_newlines : false
forced_root_block : ""
plugin:
  - fullscreen
